### ISSUE TITLE
What is the licence of this project? Is compatible with any distro of Linux?

### ISSUE THREAD

**Issue by gusbemacbe** [0xACB/javacard-config#1]
Hello,

What is the licence of this project?

Is it compatible with Arch Linux, Debian, Kali Linux, Linux Mint, Manjaro, Ubuntu and with WSL?

Thank you for your attention, help and understanding!

Gustavo Costa

**Comment by 0xACB** [comment]
Hello Gustavo,

I forgot about this project, I used it in my MSc and I didn't add a license. Feel free to use it 👍
I believe this is compatible with those Linux distributions. I used it at the time with Arch Linux and Ubuntu. Since you have shown interest in this project I will check if it still works, and I'll improve it soon.

Let me know if you have other questions. Thank you!

**Comment by gusbemacbe** [comment]
And `cd bin`. Is it `/bin` or `~/bin-linux`? It said: `bash: cd: bin: No such file or directory`.
